"""change model video

Revision ID: 57bd2e5e00d0
Revises: 
Create Date: 2022-03-15 11:42:55.092828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57bd2e5e00d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecg',
    sa.Column('sample', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('data', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['capture.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sample')
    )
    op.create_index(op.f('ix_ecg_device_id'), 'ecg', ['device_id'], unique=False)
    op.create_table('mpu',
    sa.Column('sample', sa.Integer(), nullable=False),
    sa.Column('acc_x', sa.Float(), nullable=False),
    sa.Column('acc_y', sa.Float(), nullable=False),
    sa.Column('acc_z', sa.Float(), nullable=False),
    sa.Column('gyr_x', sa.Float(), nullable=False),
    sa.Column('gyr_y', sa.Float(), nullable=False),
    sa.Column('gyr_z', sa.Float(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['capture.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sample')
    )
    op.create_index(op.f('ix_mpu_device_id'), 'mpu', ['device_id'], unique=False)
    op.drop_index('ix_data_device_id', table_name='data')
    op.drop_index('ix_data_id', table_name='data')
    op.drop_table('data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sample', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('acc_x', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('acc_y', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('acc_z', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gyr_x', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gyr_y', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gyr_z', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='data_device_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['capture.id'], name='data_owner_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='data_pkey')
    )
    op.create_index('ix_data_id', 'data', ['id'], unique=False)
    op.create_index('ix_data_device_id', 'data', ['device_id'], unique=False)
    op.drop_index(op.f('ix_mpu_device_id'), table_name='mpu')
    op.drop_table('mpu')
    op.drop_index(op.f('ix_ecg_device_id'), table_name='ecg')
    op.drop_table('ecg')
    # ### end Alembic commands ###
